#!/bin/sh
set -e

echo "==> [Desktop Entries] Setting up custom desktop entries"

SCRIPT_DIR="$HOME/git/omarchy-bootstrap"

APPLICATION_DIR="$SCRIPT_DIR/.local/share/applications"
ICONS_DIR="$SCRIPT_DIR/.local/share/icons"

echo "--> Creating application directories"
mkdir -p "$HOME/.local/share/applications"
mkdir -p "$HOME/.local/share/icons"

echo "--> Linking .desktop files"
for file in "$APPLICATION_DIR"/*.desktop; do
    [ -f "$file" ] || continue
    basefile="$(basename "$file")"
    target="$HOME/.local/share/applications/$basefile"

    echo "    -> $basefile"
    ln -sf "$file" "$target"
done


echo "--> Copying icons"
for file in "$ICONS_DIR"/*.png; do
    [ -f "$file" ] || continue
    ln -sf "$file" "$HOME/.local/share/icons/"
done

echo "--> Backing up unwanted desktop entries"
# List of entries to disable
for filename in \
    "Basecamp.desktop" \
    "dropbox.desktop" \
    "Figma.desktop" \
    "Google Contacts.desktop" \
    "Google Messages.desktop" \
    "Google Photos.desktop" \
    "HEY.desktop"
do
    f="$HOME/.local/share/applications/$filename"
    if [ -e "$f" ]; then
        mv "$f" "$f.bak"
        echo "    -> backed up $filename"
    fi
done

echo "==> [Desktop Entries] Desktop entry setup complete"
